defmodule AshPg.Repo.Migrations.ApplyAshArchival do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:artists) do
      add :archived_at, :utc_datetime_usec
    end

    alter table(:artist_albums) do
      add :archived_at, :utc_datetime_usec
    end

    alter table(:albums) do
      add :archived_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:albums) do
      remove :archived_at
    end

    alter table(:artist_albums) do
      remove :archived_at
    end

    alter table(:artists) do
      remove :archived_at
    end
  end
end
