defmodule AshPg.Repo.Migrations.AddTypeCopiesSoldToAlbum do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:albums) do
      add :type, :text, null: false, default: "studio"
      add :copies_sold, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:albums) do
      remove :copies_sold
      remove :type
    end
  end
end
