defmodule AshPg.Repo.Migrations.AddBioToArtist do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:artists) do
      add :bio, :map
    end
  end

  def down do
    alter table(:artists) do
      remove :bio
    end
  end
end
