defmodule AshPg.Repo.Migrations.CreateArtistAlbum do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:artist_albums, primary_key: false) do
      add :artist_id,
          references(:artists,
            column: :id,
            name: "artist_albums_artist_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :album_id,
          references(:albums,
            column: :id,
            name: "artist_albums_album_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:artist_albums, "artist_albums_artist_id_fkey")

    drop constraint(:artist_albums, "artist_albums_album_id_fkey")

    drop table(:artist_albums)
  end
end
